// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_LIGHTAPPSCREEN_H
#define UI_LIGHTAPPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_LightAppScreen
extern void ui_LightAppScreen_screen_init(void);
extern void ui_LightAppScreen_screen_destroy(void);
extern void ui_event_LightAppScreen( lv_event_t * e);
extern lv_obj_t *ui_LightAppScreen;
extern lv_obj_t *ui_LightAppTitle;
extern lv_obj_t *ui_LightLabel1;
extern lv_obj_t *ui_LightSwitch1;
extern lv_obj_t *ui_LightCircleBorder;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

