// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_LightAppScreen = NULL;lv_obj_t *ui_LightAppTitle = NULL;lv_obj_t *ui_LightLabel1 = NULL;lv_obj_t *ui_LightSwitch1 = NULL;lv_obj_t *ui_LightCircleBorder = NULL;
// event funtions
void ui_event_LightAppScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_HomeScreen, LV_SCR_LOAD_ANIM_OVER_TOP, 200, 0, &ui_HomeScreen_screen_init);
}
}

// build funtions

void ui_LightAppScreen_screen_init(void)
{
ui_LightAppScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_LightAppScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_LightAppScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LightAppScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_LightAppScreen, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_LightAppScreen, -20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LightAppTitle = lv_label_create(ui_LightAppScreen);
lv_obj_set_width( ui_LightAppTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LightAppTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LightAppTitle, 0 );
lv_obj_set_y( ui_LightAppTitle, -125 );
lv_obj_set_align( ui_LightAppTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_LightAppTitle,"LIGHTS");
lv_obj_set_style_text_color(ui_LightAppTitle, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LightAppTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LightAppTitle, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LightLabel1 = lv_label_create(ui_LightAppScreen);
lv_obj_set_width( ui_LightLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LightLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LightLabel1, 40 );
lv_obj_set_y( ui_LightLabel1, -40 );
lv_obj_set_align( ui_LightLabel1, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_LightLabel1,"Salon");
lv_obj_set_style_text_color(ui_LightLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LightLabel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LightLabel1, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LightSwitch1 = lv_switch_create(ui_LightAppScreen);
lv_obj_set_width( ui_LightSwitch1, 80);
lv_obj_set_height( ui_LightSwitch1, 40);
lv_obj_set_x( ui_LightSwitch1, 120 );
lv_obj_set_y( ui_LightSwitch1, -40 );
lv_obj_set_align( ui_LightSwitch1, LV_ALIGN_CENTER );

lv_obj_set_style_bg_color(ui_LightSwitch1, lv_color_hex(0x262626), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LightSwitch1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LightSwitch1, lv_color_hex(0x264861), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_LightSwitch1, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

lv_obj_set_style_bg_color(ui_LightSwitch1, lv_color_hex(0x787878), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LightSwitch1, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_LightSwitch1, &ui_img_lightoff3_png, LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_color(ui_LightSwitch1, lv_color_hex(0x999999), LV_PART_KNOB | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_LightSwitch1, 255, LV_PART_KNOB| LV_STATE_CHECKED);
lv_obj_set_style_bg_img_src( ui_LightSwitch1, &ui_img_lighton3_png, LV_PART_KNOB | LV_STATE_CHECKED );

ui_LightCircleBorder = lv_img_create(ui_LightAppScreen);
lv_img_set_src(ui_LightCircleBorder, &ui_img_ellipse_22_png);
lv_obj_set_width( ui_LightCircleBorder, LV_SIZE_CONTENT);  /// 412
lv_obj_set_height( ui_LightCircleBorder, LV_SIZE_CONTENT);   /// 412
lv_obj_set_align( ui_LightCircleBorder, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_LightCircleBorder, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_LightCircleBorder, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_LightAppScreen, ui_event_LightAppScreen, LV_EVENT_ALL, NULL);

}

void ui_LightAppScreen_screen_destroy(void)
{
   if (ui_LightAppScreen) lv_obj_del(ui_LightAppScreen);

// NULL screen variables
ui_LightAppScreen= NULL;
ui_LightAppTitle= NULL;
ui_LightLabel1= NULL;
ui_LightSwitch1= NULL;
ui_LightCircleBorder= NULL;

}
