// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_HomeScreen.h"
#include "ui_FindAppScreen.h"
#include "ui_LightAppScreen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_background_png);   // assets/Background.png
LV_IMG_DECLARE( ui_img_lightapp_png);   // assets/LightApp.png
LV_IMG_DECLARE( ui_img_findappicon_png);   // assets/FindAppIcon.png
LV_IMG_DECLARE( ui_img_1280652718);   // assets/batterie-vide (1).png
LV_IMG_DECLARE( ui_img_lightoff3_png);   // assets/LightOff3.png
LV_IMG_DECLARE( ui_img_lighton3_png);   // assets/LightOn3.png
LV_IMG_DECLARE( ui_img_ellipse_22_png);   // assets/Ellipse 22.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
