// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_SoundManagerScreen = NULL;lv_obj_t *ui_DurationSlider = NULL;lv_obj_t *ui_VolumeManagerArc = NULL;lv_obj_t *ui_SoundPlayerSwitch = NULL;lv_obj_t *ui_VolumeLabel = NULL;lv_obj_t *ui_SoundManagerBorder = NULL;lv_obj_t *ui_DurationLabel = NULL;
// event funtions
void ui_event_SoundManagerScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_HomeScreen, LV_SCR_LOAD_ANIM_OVER_TOP, 100, 0, &ui_HomeScreen_screen_init);
}
}

void ui_event_VolumeManagerArc( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( ui_VolumeLabel, target, "", "%");
}
}

// build funtions

void ui_SoundManagerScreen_screen_init(void)
{
ui_SoundManagerScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SoundManagerScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SoundManagerScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SoundManagerScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DurationSlider = lv_slider_create(ui_SoundManagerScreen);
lv_slider_set_value( ui_DurationSlider, 4, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_DurationSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_DurationSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_DurationSlider, 240);
lv_obj_set_height( ui_DurationSlider, 15);
lv_obj_set_x( ui_DurationSlider, 80 );
lv_obj_set_y( ui_DurationSlider, 110 );
lv_obj_set_align( ui_DurationSlider, LV_ALIGN_LEFT_MID );
lv_obj_set_style_bg_color(ui_DurationSlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DurationSlider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VolumeManagerArc = lv_arc_create(ui_SoundManagerScreen);
lv_obj_set_width( ui_VolumeManagerArc, 218);
lv_obj_set_height( ui_VolumeManagerArc, 213);
lv_obj_set_x( ui_VolumeManagerArc, 0 );
lv_obj_set_y( ui_VolumeManagerArc, -50 );
lv_obj_set_align( ui_VolumeManagerArc, LV_ALIGN_CENTER );
lv_arc_set_value(ui_VolumeManagerArc, 50);
lv_arc_set_bg_angles(ui_VolumeManagerArc,180,0);

ui_SoundPlayerSwitch = lv_switch_create(ui_SoundManagerScreen);
lv_obj_set_width( ui_SoundPlayerSwitch, 103);
lv_obj_set_height( ui_SoundPlayerSwitch, 55);
lv_obj_set_x( ui_SoundPlayerSwitch, 0 );
lv_obj_set_y( ui_SoundPlayerSwitch, 30 );
lv_obj_set_align( ui_SoundPlayerSwitch, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_SoundPlayerSwitch, lv_color_hex(0xA0A0A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SoundPlayerSwitch, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SoundPlayerSwitch, lv_color_hex(0x313134), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SoundPlayerSwitch, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_SoundPlayerSwitch, &ui_img_stop_png, LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_color(ui_SoundPlayerSwitch, lv_color_hex(0x313134), LV_PART_KNOB | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_SoundPlayerSwitch, 255, LV_PART_KNOB| LV_STATE_CHECKED);
lv_obj_set_style_bg_img_src( ui_SoundPlayerSwitch, &ui_img_resume_png, LV_PART_KNOB | LV_STATE_CHECKED );

ui_VolumeLabel = lv_label_create(ui_SoundManagerScreen);
lv_obj_set_width( ui_VolumeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VolumeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_VolumeLabel, 0 );
lv_obj_set_y( ui_VolumeLabel, -90 );
lv_obj_set_align( ui_VolumeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_VolumeLabel,"50%");
lv_obj_set_style_text_color(ui_VolumeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_VolumeLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_VolumeLabel, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SoundManagerBorder = lv_img_create(ui_SoundManagerScreen);
lv_img_set_src(ui_SoundManagerBorder, &ui_img_ellipse_22_png);
lv_obj_set_width( ui_SoundManagerBorder, LV_SIZE_CONTENT);  /// 412
lv_obj_set_height( ui_SoundManagerBorder, LV_SIZE_CONTENT);   /// 412
lv_obj_set_align( ui_SoundManagerBorder, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SoundManagerBorder, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_SoundManagerBorder, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_DurationLabel = lv_label_create(ui_SoundManagerScreen);
lv_obj_set_width( ui_DurationLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DurationLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DurationLabel, 0 );
lv_obj_set_y( ui_DurationLabel, 140 );
lv_obj_set_align( ui_DurationLabel, LV_ALIGN_CENTER );
lv_obj_set_style_text_color(ui_DurationLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DurationLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DurationLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_VolumeManagerArc, ui_event_VolumeManagerArc, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SoundManagerScreen, ui_event_SoundManagerScreen, LV_EVENT_ALL, NULL);

}

void ui_SoundManagerScreen_screen_destroy(void)
{
   if (ui_SoundManagerScreen) lv_obj_del(ui_SoundManagerScreen);

// NULL screen variables
ui_SoundManagerScreen= NULL;
ui_DurationSlider= NULL;
ui_VolumeManagerArc= NULL;
ui_SoundPlayerSwitch= NULL;
ui_VolumeLabel= NULL;
ui_SoundManagerBorder= NULL;
ui_DurationLabel= NULL;

}
