// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_FindAppScreen = NULL;lv_obj_t *ui_FindAppTitle = NULL;
// event funtions
void ui_event_FindAppScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_HomeScreen, LV_SCR_LOAD_ANIM_OVER_TOP, 200, 0, &ui_HomeScreen_screen_init);
}
}

// build funtions

void ui_FindAppScreen_screen_init(void)
{
ui_FindAppScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_FindAppScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_FindAppTitle = lv_label_create(ui_FindAppScreen);
lv_obj_set_width( ui_FindAppTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FindAppTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FindAppTitle, 0 );
lv_obj_set_y( ui_FindAppTitle, -125 );
lv_obj_set_align( ui_FindAppTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_FindAppTitle,"FIND");
lv_obj_set_style_text_font(ui_FindAppTitle, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_FindAppScreen, ui_event_FindAppScreen, LV_EVENT_ALL, NULL);

}

void ui_FindAppScreen_screen_destroy(void)
{
   if (ui_FindAppScreen) lv_obj_del(ui_FindAppScreen);

// NULL screen variables
ui_FindAppScreen= NULL;
ui_FindAppTitle= NULL;

}
