// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_FINDAPPSCREEN_H
#define UI_FINDAPPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_FindAppScreen
extern void ui_FindAppScreen_screen_init(void);
extern void ui_FindAppScreen_screen_destroy(void);
extern void ui_event_FindAppScreen( lv_event_t * e);
extern lv_obj_t *ui_FindAppScreen;
extern lv_obj_t *ui_FindAppTitle;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

