// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_HomeScreen = NULL;lv_obj_t *ui_Hour = NULL;lv_obj_t *ui_LightAppButton = NULL;lv_obj_t *ui_FindAppButton = NULL;lv_obj_t *ui_BatteryState = NULL;lv_obj_t *ui_BatteryLabel = NULL;lv_obj_t *ui_EnergyPanel1 = NULL;lv_obj_t *ui_EnergyPanel2 = NULL;lv_obj_t *ui_EnergyPanel3 = NULL;
// event funtions
void ui_event_LightAppButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_LightAppScreen, LV_SCR_LOAD_ANIM_OVER_TOP, 200, 0, &ui_LightAppScreen_screen_init);
}
}

void ui_event_FindAppButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_FindAppScreen, LV_SCR_LOAD_ANIM_OVER_TOP, 200, 0, &ui_FindAppScreen_screen_init);
}
}

// build funtions

void ui_HomeScreen_screen_init(void)
{
ui_HomeScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_HomeScreen, lv_color_hex(0x13E7D2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HomeScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_HomeScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_HomeScreen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_HomeScreen, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_HomeScreen, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Hour = lv_label_create(ui_HomeScreen);
lv_obj_set_width( ui_Hour, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Hour, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Hour, 0 );
lv_obj_set_y( ui_Hour, -125 );
lv_obj_set_align( ui_Hour, LV_ALIGN_CENTER );
lv_label_set_text(ui_Hour,"12:34");
lv_obj_set_style_text_color(ui_Hour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Hour, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Hour, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LightAppButton = lv_imgbtn_create(ui_HomeScreen);
lv_imgbtn_set_src(ui_LightAppButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_lightapp_png, NULL);
lv_obj_set_width( ui_LightAppButton, 64);
lv_obj_set_height( ui_LightAppButton, 64);
lv_obj_set_x( ui_LightAppButton, -66 );
lv_obj_set_y( ui_LightAppButton, -6 );
lv_obj_set_align( ui_LightAppButton, LV_ALIGN_CENTER );

ui_FindAppButton = lv_imgbtn_create(ui_HomeScreen);
lv_imgbtn_set_src(ui_FindAppButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_findappicon_png, NULL);
lv_obj_set_width( ui_FindAppButton, 64);
lv_obj_set_height( ui_FindAppButton, 64);
lv_obj_set_x( ui_FindAppButton, 61 );
lv_obj_set_y( ui_FindAppButton, -7 );
lv_obj_set_align( ui_FindAppButton, LV_ALIGN_CENTER );

ui_BatteryState = lv_img_create(ui_HomeScreen);
lv_img_set_src(ui_BatteryState, &ui_img_1280652718);
lv_obj_set_width( ui_BatteryState, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BatteryState, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BatteryState, 0 );
lv_obj_set_y( ui_BatteryState, 170 );
lv_obj_set_align( ui_BatteryState, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BatteryState, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BatteryState, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BatteryLabel = lv_label_create(ui_HomeScreen);
lv_obj_set_width( ui_BatteryLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BatteryLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BatteryLabel, 0 );
lv_obj_set_y( ui_BatteryLabel, 140 );
lv_obj_set_align( ui_BatteryLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_BatteryLabel,"100%");
lv_obj_set_style_text_color(ui_BatteryLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BatteryLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BatteryLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_EnergyPanel1 = lv_obj_create(ui_HomeScreen);
lv_obj_set_width( ui_EnergyPanel1, 14);
lv_obj_set_height( ui_EnergyPanel1, 25);
lv_obj_set_x( ui_EnergyPanel1, -20 );
lv_obj_set_y( ui_EnergyPanel1, 170 );
lv_obj_set_align( ui_EnergyPanel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_EnergyPanel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_EnergyPanel1, lv_color_hex(0xFFC000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_EnergyPanel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_EnergyPanel2 = lv_obj_create(ui_HomeScreen);
lv_obj_set_width( ui_EnergyPanel2, 14);
lv_obj_set_height( ui_EnergyPanel2, 25);
lv_obj_set_x( ui_EnergyPanel2, -1 );
lv_obj_set_y( ui_EnergyPanel2, 170 );
lv_obj_set_align( ui_EnergyPanel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_EnergyPanel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_EnergyPanel2, lv_color_hex(0xFFC000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_EnergyPanel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_EnergyPanel3 = lv_obj_create(ui_HomeScreen);
lv_obj_set_width( ui_EnergyPanel3, 14);
lv_obj_set_height( ui_EnergyPanel3, 25);
lv_obj_set_x( ui_EnergyPanel3, 18 );
lv_obj_set_y( ui_EnergyPanel3, 170 );
lv_obj_set_align( ui_EnergyPanel3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_EnergyPanel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_EnergyPanel3, lv_color_hex(0xFFC000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_EnergyPanel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_LightAppButton, ui_event_LightAppButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_FindAppButton, ui_event_FindAppButton, LV_EVENT_ALL, NULL);

}

void ui_HomeScreen_screen_destroy(void)
{
   if (ui_HomeScreen) lv_obj_del(ui_HomeScreen);

// NULL screen variables
ui_HomeScreen= NULL;
ui_Hour= NULL;
ui_LightAppButton= NULL;
ui_FindAppButton= NULL;
ui_BatteryState= NULL;
ui_BatteryLabel= NULL;
ui_EnergyPanel1= NULL;
ui_EnergyPanel2= NULL;
ui_EnergyPanel3= NULL;

}
