// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_HOMESCREEN_H
#define UI_HOMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HomeScreen
extern void ui_HomeScreen_screen_init(void);
extern void ui_HomeScreen_screen_destroy(void);
extern lv_obj_t *ui_HomeScreen;
extern lv_obj_t *ui_Hour;
extern void ui_event_LightAppButton( lv_event_t * e);
extern lv_obj_t *ui_LightAppButton;
extern void ui_event_FindAppButton( lv_event_t * e);
extern lv_obj_t *ui_FindAppButton;
extern lv_obj_t *ui_BatteryState;
extern lv_obj_t *ui_BatteryLabel;
extern lv_obj_t *ui_EnergyPanel1;
extern lv_obj_t *ui_EnergyPanel2;
extern lv_obj_t *ui_EnergyPanel3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

