// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SOUNDMANAGERSCREEN_H
#define UI_SOUNDMANAGERSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SoundManagerScreen
extern void ui_SoundManagerScreen_screen_init(void);
extern void ui_SoundManagerScreen_screen_destroy(void);
extern void ui_event_SoundManagerScreen( lv_event_t * e);
extern lv_obj_t *ui_SoundManagerScreen;
extern lv_obj_t *ui_DurationSlider;
extern void ui_event_VolumeManagerArc( lv_event_t * e);
extern lv_obj_t *ui_VolumeManagerArc;
extern lv_obj_t *ui_SoundPlayerSwitch;
extern lv_obj_t *ui_VolumeLabel;
extern lv_obj_t *ui_SoundManagerBorder;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

